Feature/contacts
Saprik13/iceream-project-t19 pull request #8
Opened 2022-01-30 14:41 UTC by rmnmaksimenko

Предварительная секция контактов.
Есть варианты под моб, планшет и десктоп.
Без модалки.

2022-01-30 18:28 UTC, Saprik13 requested changes

2022-01-30 18:28 UTC, Saprik13 commented on src/sass/layouts/_contacts.scss
> +  @media screen and (min-width: 768px) {
для таблетки надо так (min-width: 768px) and (max-width: $tablet), поменяй везде

2022-01-30 18:28 UTC, Saprik13 commented on src/partials/contacts.html
> +<section class="container contacts-section section">
section class="contacts-section section"
div class="container"

2022-01-30 18:28 UTC, Saprik13 commented on src/partials/contacts.html
> +  <div class="contacts__background"></div>
пока так, на финальной сборке пересмотрю

2022-01-30 18:28 UTC, Saprik13 commented on src/partials/contacts.html
> +    <li class="contacts__list">
лишки contacts__item

2022-01-30 18:28 UTC, Saprik13 commented on src/partials/contacts.html
> +      <p class="contacts__building--first">cafe</p>
p class="contacts__text contacts__text--orange-bcg"
смотри в чём суть присвоения классов, когда мы даём тэгу класс, мы не описываем его содержимое, а описываем тэг, то есть, любой h это title, любой р это text лишки это item любая а это link и так далее, тут contacts__text--orange-bcg описывает то что модифицирует - фон
по этой логике пройдись пожалуйста по коду и поменяй везде где нужно

2022-01-30 18:28 UTC, Saprik13 commented on src/sass/layouts/_contacts.scss
> +@mixin contacts-building($width, $height, $back-color, $fontsize, $border) {
положи в папку mixins

2022-01-30 18:28 UTC, Saprik13 commented on src/partials/contacts.html
> +      <ul class="contacts-work">
ul class="contacts-timing"

2022-01-30 18:28 UTC, Saprik13 commented on src/partials/contacts.html
> +      <p class="contacts__text">Fusce ut velit laoreet, tempus arcu molestie vulputate</p>
concacts__header, contacts-work__day,  contacts-work__day, contacts-work__time, contacts__contacts всё что одинаковый стиль вынеси в отдельный класс и добавь в __typography

2022-01-30 18:28 UTC, Saprik13 commented on src/sass/layouts/_contacts.scss
> +  font-family: DM Sans;
не нужен

2022-01-31 14:05 UTC, rmnmaksimenko commented on src/sass/layouts/_contacts.scss
> +  font-family: DM Sans;
убираю

2022-01-31 14:08 UTC, rmnmaksimenko commented on src/sass/layouts/_contacts.scss
> +  @media screen and (min-width: 768px) {
Код так написан, потому что все стили для десктопа переопределяются в своём медиазапросе после планшета. Если бы в планшетном варианте, например, были какие-то уникальные бордеры, менять код было бы смысл.

2022-01-31 14:11 UTC, rmnmaksimenko commented on src/partials/contacts.html
> +    <li class="contacts__list">
меняю листы на айтемы

2022-01-31 14:26 UTC, rmnmaksimenko commented on src/partials/contacts.html
> +      <p class="contacts__text">Fusce ut velit laoreet, tempus arcu molestie vulputate</p>
не получится. между ними есть различия.

2022-01-31 14:26 UTC, rmnmaksimenko commented on src/partials/contacts.html
> +      <ul class="contacts-work">
поменял

2022-01-31 14:32 UTC, rmnmaksimenko commented on src/sass/layouts/_contacts.scss
> +@mixin contacts-building($width, $height, $back-color, $fontsize, $border) {
положил, теперь надо добавить в main.scss через импорт
@import './mixins/contacts-building';

2022-01-31 14:32 UTC, rmnmaksimenko commented on src/partials/contacts.html
> +      <p class="contacts__building--first">cafe</p>
поменял всё, что нашёл

2022-01-31 14:33 UTC, rmnmaksimenko commented on src/partials/contacts.html
> +<section class="container contacts-section section">
поменял

2022-01-31 15:20 UTC, Saprik13 approved these changes

2022-01-31 15:20 UTC, merged